### ISSUE TITLE
MDP Executor TODO list

### ISSUE THREAD

**Issue by hawesie** [bfalacerda/strands_executive#9]
# Features
- [ ] Monitoring policy execution time
- [x] On-demand tasks
- [x] Logging of task events
- [x] Publishing a rough schedule
- [x] Pause and restart execution
- [x] Reimplementing `is_task_interruptible` to deal with task batches and correctly handling tasks during interruptions
# Unit Tests
- [x] Normal tasks
- [x] Normal + time-critical tasks (written, but not run for meaningful sets of tasks)
- [x] Start/stop execution with normal tasks
- [x] On-demand tasks
